//
//  MainScreenModels.swift
//  L-Tech-test
//
//  Created by Рамил Гаджиев on 20.10.2021.
//  Copyright (c) 2021 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//
import Foundation

typealias ModelCellViewModel = MainScreen.ShowModels.ViewModel.ModelCellViewModel

protocol CellIdentifiable {
    var cellIdentifier: String { get }
}


enum MainScreen {
    
    // MARK: Use cases
    enum ShowModels {
        struct Request {

        }
        
        struct Response {
            let models: [MyDetailScreenModel]?
        }
        
        struct ViewModel {
            struct ModelCellViewModel: CellIdentifiable {
                var title: String?
                var text: String?
                var date: Date?
                var imageString: String?
                var cellIdentifier: String {
                    Celll.identifier
                }
                
                init(myDetailScreenModel: MyDetailScreenModel) {
                    title = myDetailScreenModel.title
                    text = myDetailScreenModel.text
                    date = myDetailScreenModel.date
                    imageString = myDetailScreenModel.image
                }
            }
            let rows: [CellIdentifiable]
        }
    }
}
