//
//  MainScreenPresenter.swift
//  L-Tech-test
//
//  Created by Рамил Гаджиев on 20.10.2021.
//  Copyright (c) 2021 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//
import Foundation


protocol MainScreenPresentationLogic {
    func presentModels(response: MainScreen.ShowModels.Response)
}

class MainScreenPresenter: MainScreenPresentationLogic {

    
    weak var viewController: MainScreenDisplayLogic?
    
    func presentModels(response: MainScreen.ShowModels.Response) {
        var rows: [ModelCellViewModel] = []
        response.models?.forEach({ model in
            rows.append(ModelCellViewModel(myDetailScreenModel: model))
        })
        let viewModel = MainScreen.ShowModels.ViewModel(rows: rows)
        viewController?.displayModels(viewModel: viewModel)
    }
}
