//
//  MainScreenRouter.swift
//  L-Tech-test
//
//  Created by Рамил Гаджиев on 20.10.2021.
//  Copyright (c) 2021 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

@objc protocol MainScreenRoutingLogic {
    func routeToDetailScreen()
}

protocol MainScreenDataPassing {
    var dataStore: MainScreenDataStore? { get }
}

class MainScreenRouter: NSObject, MainScreenRoutingLogic, MainScreenDataPassing {
    
    weak var viewController: MainScreenViewController?
    var dataStore: MainScreenDataStore?
    
    // MARK: Routing
    func routeToDetailScreen() {
            let mainVC = self.viewController
            let mainDS = self.dataStore
            let detailScreenVC = DetailScreenViewController()
            var detailScreenDS = detailScreenVC.router?.dataStore
            self.passDataToDetailScreen(source: mainDS!, destination: &detailScreenDS!)
            self.navigateToDetailScreen(source: mainVC!, destination: detailScreenVC)
    }
    
    // MARK: Navigation
    func navigateToDetailScreen(source: MainScreenViewController, destination: DetailScreenViewController) {
        source.navigationController?.pushViewController(destination, animated: true)
    }
    
    // MARK: Passing data
    func passDataToDetailScreen(source: MainScreenDataStore, destination: inout DetailScreenDataStore) {
        guard let indexPath = viewController?.ttableView.indexPathForSelectedRow else { return }
        destination.model = source.models?[indexPath.row]
    }
}
