//
//  MainScreenInteractor.swift
//  L-Tech-test
//
//  Created by Рамил Гаджиев on 20.10.2021.
//  Copyright (c) 2021 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

protocol MainScreenBusinessLogic {
    func provideMainScreen()
    func reloadTableView()
    func sortByDate()
    func sortByServer()
}

protocol MainScreenDataStore {
    var models: [MyDetailScreenModel]? { get set }
}

class MainScreenInteractor: MainScreenBusinessLogic, MainScreenDataStore {
    

    
    var models: [MyDetailScreenModel]?
    var presenter: MainScreenPresentationLogic?
    var worker: MainScreenWorker?
    
    func provideMainScreen() {
        let response = MainScreen.ShowModels.Response(models: models)
        presenter?.presentModels(response: response)
    }
    
    func reloadTableView() {
        let worker = MainScreenWorker()
        worker.fetchModels {[weak self] models in
            self?.models = models
            self?.provideMainScreen()
        }
    }
    
    func sortByDate() {
        guard models != nil else { return }
        models!.sort{$0.date! > $1.date!}
        self.provideMainScreen()
    }
    
    func sortByServer() {
        guard models != nil else { return }
        models!.sort{$0.sort! < $1.sort!}
        self.provideMainScreen()
    }
}
