//
//  DetailScreenPresenter.swift
//  L-Tech-test
//
//  Created by Рамил Гаджиев on 20.10.2021.
//  Copyright (c) 2021 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

protocol DetailScreenPresentationLogic {
    func presentScreenDetail(response: DetailScreen.ShowDetails.Response)
}

class DetailScreenPresenter: DetailScreenPresentationLogic {
    
    weak var viewController: DetailScreenDisplayLogic?
    
    func presentScreenDetail(response: DetailScreen.ShowDetails.Response) {
        
        let viewModel = DetailScreen.ShowDetails.ViewModel(
            modelTitle: response.modelTitle ?? "",
            modelText: response.modelText ?? "",
            imageData: response.imageData ?? "noImage".data(using: .utf8)!
        )
        viewController?.displayDetailScreen(viewModel: viewModel)
    }
}
